Now passing all tests except for:
  1) Parser: API can save state:
     Error: Expected 0 to be 11
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toBe (node_modules/expect/lib/Expectation.js:66:28)
      at Context.<anonymous> (test/parser.test.js:42:27)

  2) Parser: API can rewind:
     Error: Expected 0 to be 11
      at assert (node_modules/expect/lib/assert.js:29:9)
      at Expectation.toBe (node_modules/expect/lib/Expectation.js:66:28)
      at Context.<anonymous> (test/parser.test.js:54:27)

  3) Parser: API restores line numbers:
     TypeError: Cannot read property 'line' of undefined
      at Context.<anonymous> (test/parser.test.js:75:33)

  4) Parser: API restores column number:
     TypeError: Cannot read property 'line' of undefined
      at Context.<anonymous> (test/parser.test.js:89:29)

Rewinding isn't supported in this branch and probably won't be, since
its focus is parsing quickly according to an unambiguous grammar.